web: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 3
worker: celery -A app.celery_app:celery worker --loglevel=info --concurrency=4
beat: celery -A app.celery_app:celery beat --loglevel=info
